#ifndef NAVBOARD_CONFIG_H
#define NAVBOARD_CONFIG_H

#define SHELL "/bin/sh"
#define MAX_X_EVENTS 32
#define MAX_BOARDS 256
#define DEFAULT_DOCK_TYPE BOTTOM
#define DEFAULT_THICKNESS 40
#define NUM_FD_LISTENERS 2

#define DEFAULT_OUTLINE_COLOR 0
#define DEFAULT_TEXT_COLOR 0xfefefe
#define DEFAULT_CELL_COLOR 0x14313d
#define DEFAULT_CELL_COLOR_PRESSED 0x005577

#define DEFAULT_CELL_COLOR_DISABLED 0x103030


#define DEFAULT_FONT_NAME "LiberationMono-Regular.ttf"
#define DEFAULT_FONT_SIZE 16

#define WINDOW_MASKS (XCB_EVENT_MASK_BUTTON_PRESS | XCB_EVENT_MASK_BUTTON_RELEASE | XCB_EVENT_MASK_BUTTON_MOTION | XCB_EVENT_MASK_EXPOSURE | XCB_EVENT_MASK_STRUCTURE_NOTIFY)

#endif
