#ifndef NAVBOARD_CONFIG_H
#define NAVBOARD_CONFIG_H

#define SHELL "/bin/sh"
#define MAX_X_EVENTS 32
#define MAX_BOARDS 8
#define DEFAULT_DOCK_TYPE BOTTOM
#define DEFAULT_THICKNESS 40
#define NUM_FD_LISTENERS 2

#define WINDOW_MASKS (XCB_EVENT_MASK_BUTTON_PRESS | XCB_EVENT_MASK_BUTTON_RELEASE | XCB_EVENT_MASK_EXPOSURE | XCB_EVENT_MASK_STRUCTURE_NOTIFY)

#endif
