#include "../navboard.h"
Key keys_dvorak[] = {
    {XK_Meta_L},
    {XK_grave},
    {XK_1},
    {XK_2},
    {XK_3},
    {XK_4},
    {XK_5},
    {XK_6},
    {XK_7},
    {XK_8},
    {XK_9},
    {XK_0},
    {XK_bracketleft},
    {XK_bracketright},
    {XK_BackSpace, .weight = 2 },
    {0 },       // New row
    {XK_Tab},
    {XK_apostrophe},
    {XK_comma},
    {XK_period},
    {XK_p},
    {XK_y},
    {XK_f},
    {XK_g},
    {XK_c},
    {XK_r},
    {XK_l},
    {XK_slash},
    {XK_equal},
    {XK_backslash},
    {0},// New row
    {XK_Hyper_L, .weight = 2 },
    {XK_a},
    {XK_o},
    {XK_e},
    {XK_u},
    {XK_i},
    {XK_d},
    {XK_h},
    {XK_t},
    {XK_n},
    {XK_s},
    {XK_minus},
    {XK_Return, .weight = 3 },
    {0 },       // New row
    {XK_Shift_R, .weight = 1 },
    {XK_Shift_L, .weight = 2 },
    {XK_semicolon},
    {XK_q},
    {XK_j},
    {XK_k},
    {XK_x},
    {XK_b},
    {XK_m},
    {XK_w},
    {XK_v},
    {XK_z},
    {XK_Shift_R, .weight = 2 },
    {0}, /* New row */
    {XK_Control_L, .weight = 2 },
    {XK_Super_L, .weight = 2 },
    {XK_Alt_L, .weight = 2 },
    {XK_space, .weight = 5 },
    {XK_Alt_R, .weight = 2 },
    {XK_Menu, .weight = 1 },
    {XK_Control_R, .weight = 2 },
};
REGISTER(dvorak, keys_dvorak);

