#include "../navboard.h"
Key keys_qwerty[] = {
    {XK_grave},
    {XK_1},
    {XK_2},
    {XK_3},
    {XK_4},
    {XK_5},
    {XK_6},
    {XK_7},
    {XK_8},
    {XK_9},
    {XK_0},
    {XK_minus},
    {XK_plus},
    {XK_BackSpace, .weight = 2},
    {0 }, /* New row */
    {XK_Tab},
    {XK_q},
    {XK_w},
    {XK_e},
    {XK_r},
    {XK_t},
    {XK_y},
    {XK_u},
    {XK_i},
    {XK_o},
    {XK_p},
    {XK_bracketleft},
    {XK_bracketright},
    {XK_backslash},
    {0}, /* New row */
    {XK_Shift_L, .label="Shift Lock", .weight = 2, .flags = LOCK},
    {XK_a},
    {XK_s},
    {XK_d},
    {XK_f},
    {XK_g},
    {XK_h},
    {XK_j},
    {XK_k},
    {XK_l},
    {XK_semicolon},
    {XK_apostrophe},
    {XK_Return, .weight = 3},
    {0}, /* New row */
    {XK_Shift_L, .weight = 3},
    {XK_z},
    {XK_x},
    {XK_c},
    {XK_v},
    {XK_b},
    {XK_n},
    {XK_m},
    {XK_comma, .weight = 1},
    {XK_period, .weight = 1},
    {XK_slash, .weight = 1},
    {XK_Shift_R, .weight = 2},
    {0}, /* New row */
    {XK_Control_L, .weight = 1},
    {XK_Super_L, .weight = 1},
    {XK_Alt_L, .weight = 1},
    {XK_space, .weight = 5},
    {XK_Alt_R, .weight = 1},
    {XK_Control_R, .weight = 1},
};

REGISTER(qwerty, keys_qwerty);
